### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ms-ati** [waterlink/rspec-json_expectations#30]
If this ticket remains unanswered, and you are coming across this project later, we can assume it is, in fact, dead.

**Comment by ecbrodie** [comment]
I'm willing to maintain a fork of the project to keep it going. I use it on the Rails app I develop at work and I get a lot of value out of this gem.

I'll look into making a fork tonight.

**Comment by ecbrodie** [comment]
@waterlink unfortunately, life hit me last night and I didn't have time to open up Github once. But yes, I am interested in becoming the maintainer of this repository, to keep it active. Feel free to transfer ownership to me on Github. Let me know what information you need for RubyGems.

**Comment by waterlink** [comment]
Hey, @ecbrodie, I have added you as a collaborator of the repository.

Now I need your username on RubyGems, so that I can add you as a collaborator.

_(we’ll do the transfer of the repository a bit later, when you are absolutely sure that you want to continue maintaining it)_

Sorry that it took me so much time—life hit me, as well.

**Comment by waterlink** [comment]
@ecbrodie Actually, for RubyGems, I need the e-mail that you’ve use to login to RubyGems, can you send it to me in private over waterlink000 {plus} github {at} gmail {dot} com ?

**Comment by ecbrodie** [comment]
@waterlink sent :)

**Comment by waterlink** [comment]
@ecbrodie Done
